theme: jekyll-theme-cayman
title: Nagaraj Unity & Unreal Engine Developer
description: Lead programmer and team member for multiple projects employing the Unity3D engine. Responsible for entire product delivery pipeline from problem definition through solution design, programming structure, and implementation. Experienced with Agile management.
